require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FoodStocksController do

  # This should return the minimal set of attributes required to create a valid
  # FoodStock. As you add validations to FoodStock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "food" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FoodStocksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all food_stocks as @food_stocks" do
      food_stock = FoodStock.create! valid_attributes
      get :index, {}, valid_session
      assigns(:food_stocks).should eq([food_stock])
    end
  end

  describe "GET show" do
    it "assigns the requested food_stock as @food_stock" do
      food_stock = FoodStock.create! valid_attributes
      get :show, {:id => food_stock.to_param}, valid_session
      assigns(:food_stock).should eq(food_stock)
    end
  end

  describe "GET new" do
    it "assigns a new food_stock as @food_stock" do
      get :new, {}, valid_session
      assigns(:food_stock).should be_a_new(FoodStock)
    end
  end

  describe "GET edit" do
    it "assigns the requested food_stock as @food_stock" do
      food_stock = FoodStock.create! valid_attributes
      get :edit, {:id => food_stock.to_param}, valid_session
      assigns(:food_stock).should eq(food_stock)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FoodStock" do
        expect {
          post :create, {:food_stock => valid_attributes}, valid_session
        }.to change(FoodStock, :count).by(1)
      end

      it "assigns a newly created food_stock as @food_stock" do
        post :create, {:food_stock => valid_attributes}, valid_session
        assigns(:food_stock).should be_a(FoodStock)
        assigns(:food_stock).should be_persisted
      end

      it "redirects to the created food_stock" do
        post :create, {:food_stock => valid_attributes}, valid_session
        response.should redirect_to(FoodStock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved food_stock as @food_stock" do
        # Trigger the behavior that occurs when invalid params are submitted
        FoodStock.any_instance.stub(:save).and_return(false)
        post :create, {:food_stock => { "food" => "invalid value" }}, valid_session
        assigns(:food_stock).should be_a_new(FoodStock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FoodStock.any_instance.stub(:save).and_return(false)
        post :create, {:food_stock => { "food" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested food_stock" do
        food_stock = FoodStock.create! valid_attributes
        # Assuming there are no other food_stocks in the database, this
        # specifies that the FoodStock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FoodStock.any_instance.should_receive(:update).with({ "food" => "" })
        put :update, {:id => food_stock.to_param, :food_stock => { "food" => "" }}, valid_session
      end

      it "assigns the requested food_stock as @food_stock" do
        food_stock = FoodStock.create! valid_attributes
        put :update, {:id => food_stock.to_param, :food_stock => valid_attributes}, valid_session
        assigns(:food_stock).should eq(food_stock)
      end

      it "redirects to the food_stock" do
        food_stock = FoodStock.create! valid_attributes
        put :update, {:id => food_stock.to_param, :food_stock => valid_attributes}, valid_session
        response.should redirect_to(food_stock)
      end
    end

    describe "with invalid params" do
      it "assigns the food_stock as @food_stock" do
        food_stock = FoodStock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FoodStock.any_instance.stub(:save).and_return(false)
        put :update, {:id => food_stock.to_param, :food_stock => { "food" => "invalid value" }}, valid_session
        assigns(:food_stock).should eq(food_stock)
      end

      it "re-renders the 'edit' template" do
        food_stock = FoodStock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FoodStock.any_instance.stub(:save).and_return(false)
        put :update, {:id => food_stock.to_param, :food_stock => { "food" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested food_stock" do
      food_stock = FoodStock.create! valid_attributes
      expect {
        delete :destroy, {:id => food_stock.to_param}, valid_session
      }.to change(FoodStock, :count).by(-1)
    end

    it "redirects to the food_stocks list" do
      food_stock = FoodStock.create! valid_attributes
      delete :destroy, {:id => food_stock.to_param}, valid_session
      response.should redirect_to(food_stocks_url)
    end
  end

end
